### ISSUE TITLE
Håndtering af Producent ID mangler i producer for observationen

### ISSUE THREAD

**Issue by mbumedcom** [hl7dk/dk-core#105]
Når man sender laboratoriesvar er det på nuværende tidspunkt et krav , at man skal sende et Producent ID.  Producent ID er et 3 bogstavs kode for det laboratorie/organisation som har udarbejdet svar og udstilles af MedCom.  link til oversigten: https://svn.medcom.dk/svn/drafts/Klassifikationer/Laboratorieforkortelser.xlsx 
I forbindelse med udarbejdelse af kommunale prøvesvar har vi i MedCom tilføjet en ekstra identifier til Organisationen for at tage højde for dette krav

**Comment by jkiddo** [comment]
Is this linked to any commit?

**Comment by TMHA-Trifork** [comment]
@tmsMedcom - Hvad er tanken med producent id? Skal det være et CodeSystem i MedCom regi som refereres i dk-core eller skal dk-core kun definere system?

**Comment by tmsMedcom** [comment]
Det vil være fint, at CodeSystem ligger i MedCom, og refereres i dk-core - som du har gjort.

**Comment by jkiddo** [comment]
Det lyder mere som et naming system i mine ører
