### ISSUE TITLE
ICPC2-DK

### ISSUE THREAD

**Issue by jvitrifork** [hl7dk/dk-core#11]
Can we publish the ICPC-2 DK as part of the DK Core IG?

**Comment by jkiddo** [comment]
@MichaelJohansenMedCom shouldn't the permission also come from https://www.globalfamilydoctor.com/ ?

**Comment by MichaelJohansenMedCom** [comment]
DSAM have permission from WONCA for the Danish use of ICPC

**Comment by jkiddo** [comment]
@tmsMedcom I've attached the ICPC2 for you to add to the MedCom Term server if you like
[icpc.fsh.txt](https://github.com/hl7dk/dk-core/files/9569184/icpc.fsh.txt)
