### ISSUE TITLE
Consider using compliesWithProfile for observations

### ISSUE THREAD

**Issue by jkiddo** [hl7dk/dk-core#113]
Consider using https://hl7.org/fhir/extensions/StructureDefinition-structuredefinition-compliesWithProfile.html for those instances (Observations) that conforms to e.g. the vitalsigns profile.

**Comment by tmsMedcom** [comment]
Undersøg, hvor og hvornår valideringen sker.

**Comment by jkiddo** [comment]
From the extension description:

_Asserts that instances that are valid against this profile are also automatically valid against the StructureDefinition referenced by this extension._

**Comment by jkiddo** [comment]
Fixed in https://github.com/hl7dk/dk-core/pull/132#discussion_r1653348299 using imposeProfile
