### ISSUE TITLE
Text is hard to understand

### ISSUE THREAD

**Issue by jkiddo** [hl7dk/dk-core#114]
on https://github.com/hl7dk/dk-core/blob/20c407aa90ddb4d3ba456cd9c93ff6ca2aca44f8/input/pagecontent/StructureDefinition-dk-core-basic-observation-intro.md?plain=1#L4 - what is meant by:
>Since there is an expansion of one code to each of the LOINC ValueSet and the UCUM ValueSet, it means when using these codes, the instance will not be compliant

**Comment by tmsMedcom** [comment]
Is the following more clear? "_Instances will not be compliant with HL7's Vital Signs profile when using the code '59408-5' (Oxygen saturation in Arterial blood by Pulse oximetry) from the LOINC ValueSet and the unit '{fraction}' (fraction) from the UCUM ValueSet, as these codes are not included in the ValueSets in the Vital Signs profile._"

**Comment by tmsMedcom** [comment]
@jkiddo ^ ?

**Comment by jkiddo** [comment]
Yes
