### ISSUE TITLE
Profiling of PractitionerRole

### ISSUE THREAD

**Issue by tmsMedcom** [hl7dk/dk-core#123]
Added based on decision from HL7-DK meeting on April the 30th.

**Comment by jkiddo** [comment]
I've requested more information on clinical specialties at SDS (more specifically info on http://autregwebservice.sst.dk/autregservice.asmx?op=GetAllSpecialities which should cover most of the clinical stuff while I recognize that it would be far from complete in the real world).

**Comment by jkiddo** [comment]
Profiles added in 0cd61b1fc and f64c9c930 as part of https://github.com/hl7dk/dk-core/tree/3.3.0

**Comment by jkiddo** [comment]
FYI @AsgerSDSArkitekt

**Comment by tmsMedcom** [comment]
Can this issue be closed?
