### ISSUE TITLE
RelatedPerson and Patient.contact

### ISSUE THREAD

**Issue by tmsMedcom** [hl7dk/dk-core#135]
Høringssvar:
In some systems, you can register a related person as the primary contact. Should this be supported?
Furthermore, the set of relation types does not seem to be consistent with the set from FSK.

Besluttet:
Under RelatedPerson beskriver vi, at Patient.contact bør bruges og hvis ikke kan man anvende elementet kan RelatedPerson bruges. 
Desuden udvides ValueSettet under Patient.contact til at inkludere koden for ”emergency-contact” fra HL7 CodeSystem.

**Comment by tmsMedcom** [comment]
@Kirstinerosenbeck tilføjer kode
@christiangasser-lakeside tilføjer tekstuel beskrivelse

**Comment by christiangasser-lakeside** [comment]
Tilføjet tekstuel beskrivelse på Consultation-of-v.3.2.0 branchen.

**Comment by tmsMedcom** [comment]
Can I close this issue?

**Comment by christiangasser-lakeside** [comment]
Jep :-)
