### ISSUE TITLE
RelatedPerson - Scope and usage

### ISSUE THREAD

**Issue by tmsMedcom** [hl7dk/dk-core#136]
Høringssvar:
Is it intentionally that the profiles don’t contain professional relationship to the patient? e.g., personal caretaker, physiotherapist, medical specialist etc.
If the standard should be used for an associated professional, the CPR-number should not be required.

Besluttet:
”personal caretaker” håndteres i #1. 
Gennemgå ”Scope and Usage” for profilen og sørge for at beskrive, at sundhedsfaglige relationer som fysioterapeut varetages andetsteds, fx Patient.generalPractitioner. 

AND

Høringssvar: 
What is the meaning of the comment "Note also, that the intended use of Related Person is to describe a relationship in itself and that privileges which might be associated to a relationship (e.g., power of attorney) should be expressed by other means."
One of the possible values of the relationship is "power of attorney" so how does this corelate?

Besluttet:
Formulering ændres til: ”Note also, that the intended use of Related Person is to describe a relationship, where privileges which might be associated to the relationship should be expressed by other means, e.g.the actual right associated with being power of attorney, should be described in a legally binding document, and that document can be represented with the Consent resource.”

**Comment by christiangasser-lakeside** [comment]
Fixed on Consultation-of-v.3.2.0 branch
