### ISSUE TITLE
QA-error - CodeSystem supplement

### ISSUE THREAD

**Issue by tmsMedcom** [hl7dk/dk-core#145]
The error can be found here: 
https://build.fhir.org/ig/hl7dk/dk-core/branches/3.3.0/qa.html#_scratch_repo_fsh-generated_resources_CodeSystem-dk-npu-fragment 

Possible solution: 
[#IG creation > Errors that might should be warnings](https://chat.fhir.org/#narrow/channel/179252-IG-creation/topic/Errors.20that.20might.20should.20be.20warnings)

https://hl7.org/fhir/r4/codesystem-definitions.html#CodeSystem.property - skal nok populeres

**Comment by jkiddo** [comment]
Fixed with https://github.com/hl7dk/dk-core/commit/7cd066254e42b30b3b764077d2b8bdd675712054
