### ISSUE TITLE
Add rules for Authorization Identifier

### ISSUE THREAD

**Issue by jvitrifork** [hl7dk/dk-core#15]
See http://autregwebservice.sst.dk/autregservice.asmx / https://stps.dk/da/autorisation/opslagautreg/

**Comment by jkiddo** [comment]
ID-format: https://stps.dk/da/autorisation/om-autorisationer/autorisations-id/

**Comment by jkiddo** [comment]
Already done in https://github.com/hl7dk/dk-core/blob/1.1.0/input/fsh/authorization-id-format-Invariant.fsh - closing
