### ISSUE TITLE
organisation type does not have a value set binding

### ISSUE THREAD

**Issue by Kirstinerosenbeck** [hl7dk/dk-core#22]
We talked about using the SOR organisation type SNOMED CT codes to express organisation type.

**Comment by jkiddo** [comment]
SNOMED CT code 56781000005109 does not exist in SNOMED ("center for misbrugsbehandling")

**Comment by jkiddo** [comment]
@Kirstinerosenbeck please review the list found on https://build.fhir.org/ig/hl7dk/dk-core/branches/1.1.0/ValueSet-sor-organization-type.html

**Comment by jkiddo** [comment]
@Kirstinerosenbeck - see https://chat.fhir.org/#narrow/stream/179244-snomed/topic/supported.20SNOMED.20editions.20on.20tx.2Efhir.2Eorg

**Comment by jkiddo** [comment]
Binding added with https://github.com/hl7dk/dk-core/commit/68ac94b4a134862249b7ba2da0827dd87ec2b644

**Comment by jvitrifork** [comment]
@Kirstinerosenbeck - the danish listed SNOMED concept ID's are NOT found in the latest danish edition of SNOMED. SNOMED is now loaded on the reference tx server as can be seen on https://tx.fhir.org/snomed/ . As can be seen on https://build.fhir.org/ig/hl7dk/dk-core/branches/1.1.0/qa.html# the codes cannot be found. Could you please address this finding to those who it may concern. As a reference, the can't be found on https://browser.ihtsdotools.org/?perspective=full&conceptId1=404684003&edition=MAIN/SNOMEDCT-DK/2021-09-30&release=&languages=da,en either.

**Comment by jvitrifork** [comment]
also - as a reference, the swedish edition works perfectly fine - seen at https://build.fhir.org/ig/danka74/basprofiler-r4/ValueSet-SEBaseSKRYrkeVS.json.html

**Comment by jkiddo** [comment]
Closing - since binding is done. Rest of the work is taken care of by the community

**Comment by Kirstinerosenbeck** [comment]
Rob has uploaded new danish release. We should check that it works now.
