### ISSUE TITLE
Validate STS-organisation system-value

### ISSUE THREAD

**Issue by Kirstinerosenbeck** [hl7dk/dk-core#24]
The system in KombitStsOrgIdentifier is set to: https://www.kombit.dk/sts/organisation. Did we confirm that with Kombit?

**Comment by jkiddo** [comment]
@j3h4 hvad foreslår du som system identifier?

**Comment by j3h4** [comment]
Måske bare https://kombit.dk/organisation.

Selvom den fælleskommunale løsning hedder Fælleskommunalt Organisationssystem, så hedder selve snitfladen SF1500 "Organisation".

**Comment by Kirstinerosenbeck** [comment]
Har skrevet mail til Henrik Mynderup i Kombit, og forventer at vi endeligt kan afklare senest onsdag i denne uge.

**Comment by Kirstinerosenbeck** [comment]
Vi skal iøvrigt være opmærksomme på ift. det der her diskuteres ift. navngivning, at Der står "KOMBIT STS organization identifier" i vores intro.md til organisationsprofilen

**Comment by jvitrifork** [comment]
@Kirstinerosenbeck hvad er status?

**Comment by Kirstinerosenbeck** [comment]
Kombit foretrækker  https://kombit.dk/sts/organisation

**Comment by jvitrifork** [comment]
Retter du det selv til?
