### ISSUE TITLE
DanishCivilRegistrationSystem has type.coding that does not validate

### ISSUE THREAD

**Issue by Kirstinerosenbeck** [hl7dk/dk-core#26]
type.coding is set to system: http://terminology.hl7.org/CodeSystem/v2-0203 code: NNDNK - However NNDKN is not in the given codesystem.

**Comment by jkiddo** [comment]
Fixed in https://github.com/hl7dk/dk-core/commit/5341d9665de7873d8dfcfc057c0db18a14bb9dd2
