### ISSUE TITLE
CVR-identifier error

### ISSUE THREAD

**Issue by Kirstinerosenbeck** [hl7dk/dk-core#33]
Points to som copied SOR invariant 
"
Invariants | Defined on this elementele-1: All FHIR elements must have a @value or children (: hasValue() or (children().count() > id.count()))min-digits-sor: SOR Identifiers are at minimum 11 digits long. See https://sundhedsdatastyrelsen.dk/-/media/sds/filer/rammer-og-retningslinjer/organisationsregistrering/adgang-til-sor/info-om-opbygningen-af-sor-ider.pdf"

**Comment by jkiddo** [comment]
Fixed in https://github.com/hl7dk/dk-core/commit/53954099d8da5008d8673f21ef4f659122da2146 - @tmsMedcom  feel free to review

**Comment by tmsMedcom** [comment]
Reviewed - no further comments.
