### ISSUE TITLE
cvr oid not registred correctly

### ISSUE THREAD

**Issue by Kirstinerosenbeck** [hl7dk/dk-core#34]

**Comment by jvitrifork** [comment]
FHIR generally has a huge preference for using URL's over OID's. May I suggest we use http://cvr.dk instead?

**Comment by Cambine** [comment]
The advances of using "oid" is a static and unique identification of a organization. A http adress may change..
Lets stick to the rule : use "oid" if it exists

**Comment by jvitrifork** [comment]
That is not the point here. 1.2.3.4.5 is just as static as http://abc.com - both are symbolic names. There are no requirements to whether it should resolve or not.

**Comment by jvitrifork** [comment]
The fact that anyone can register an OID undermines (exemplified by http://oid-info.com/get/2.16.840.1.113883.2.24.1.1) shows that OID's are just as flaky as anything else. The advantage of using URL's is that they to some extent are actually human readable

**Comment by Cambine** [comment]
But if the CVR register changes to DRV then the static name cvr.dk is quite confusing

**Comment by jvitrifork** [comment]
then you either stick to the address, change the address or make a new identifier

**Comment by jvitrifork** [comment]
If you really think using OID's are the best way forward and you don't think my arguments are persuasive enough, I suggest you ask on the FHIR chat why they prefer URL's over OID's.

**Comment by Cambine** [comment]
Well, my point is that if there exists a valid oid for the cvr register we shall use the oid. If not a, decision has to be made regarding which static value to use to identify the cvr.  And I have no better suggestion than "http://cvr.dk"

**Comment by jkiddo** [comment]
I'm unaware of any official registration of the CVR OID.

**Comment by jvitrifork** [comment]
Fixed with https://github.com/hl7dk/dk-core/commit/ffdb76c0fae72b31de5be5466823732c615b0930 - http://cvr.dk is chosen for now
