### ISSUE TITLE
 KombitSTSOrgIdentifier wrong invariant in value

### ISSUE THREAD

**Issue by Kirstinerosenbeck** [hl7dk/dk-core#35]
Points to some copied SOR-invariant. Kirstine spørger

**Comment by jkiddo** [comment]
SOR invariant removed: See https://github.com/hl7dk/dk-core/commit/54a7a276e0a70f6d7287b62ab3d8bf2d4f911593

**Comment by jkiddo** [comment]
Please add Kombit Invariant instead

**Comment by Kirstinerosenbeck** [comment]
Har skrevet mail til Henrik Mynderup i Kombit, og forventer at vi endeligt kan afklare senest onsdag i denne uge.

**Comment by jvitrifork** [comment]
@Kirstinerosenbeck hvad er status?

**Comment by Kirstinerosenbeck** [comment]
UUID skal angives i henhold til RFC4122

**Comment by jvitrifork** [comment]
Jeg forstår ikke - skal https://github.com/hl7dk/dk-core/blob/8d1b8536246af8112c07c7e575521caddd58f1b7/input/fsh/KombitStsOrgIdentifier.fsh#L10 være en UUID? Hvilken version af UUID?

**Comment by jvitrifork** [comment]
Fixed with https://github.com/hl7dk/dk-core/commit/78cc42155df0fe612fdfb43cf3a9e6d2924fc22c
