### ISSUE TITLE
Titles are missing on identifiers

### ISSUE THREAD

**Issue by jvitrifork** [hl7dk/dk-core#43]

**Comment by tmsMedcom** [comment]
@jvitrifork - I've added titles to all the identifiers. But it is still the 'Profile: *name*' which is shown on this page: https://build.fhir.org/ig/hl7dk/dk-core/branches/1.1.0/profiles.html. I've tried to change different parameters in the \...\dk-core\input\pagecontent\profiles.xml to get the title to be shown instead, but I haven't found a solution. Can you help?

**Comment by jkiddo** [comment]
@tmsMedcom it requires an addition in the underlying templates used by the IG publisher. @grahamegrieve will fix it for the next release in the IG publisher

**Comment by jkiddo** [comment]
Done in https://github.com/hl7dk/dk-core/commit/d810006af6427949e2caa8540838ab5a24a2fa85
