### ISSUE TITLE
Describe the use of Danish and English names

### ISSUE THREAD

**Issue by tmsMedcom** [hl7dk/dk-core#66]
Navnekonventionen er som følgende:
o Engelske kaldenavne foretrækkes hvis der er et retvisende og kendt begreb.
o Hvis ikke dette eksisterer, anvendes det danske begreb, med prefixet DA

Baseret på følgende høringssvar: 
Når alt skal være engelsk, hvorfor så Ydernummer, Kommunekode og regionskode?

**Comment by Kirstinerosenbeck** [comment]
Cannot be resolved in documentation only. GLN and EAN are both used. municipality identifier and kommunekode. Only the naming convention will be added to the IG this time around. More work needed later e.g. organization.identifier slices are all in Danish, and different from Patient.adress.extension:MunicipalityCodes and RegionalSubSivisionCpdes
