### ISSUE TITLE
Status-values from the CPR-register

### ISSUE THREAD

**Issue by tmsMedcom** [hl7dk/dk-core#70]
HL7-DK er enige om at der hverken i CPR-identifieren eller i DkCorePatient implementeres
en statusværdi fra CPR-registeret. Disse statusværdier kan være udtrykt i andre FHIR
felter, fx afdød.
• I en kommende version af DK-core implementeres en vejledning for hvordan statusværdier
kan fortolkes i DK-core.

Baseret på følgende høringssvar:
Er det et bevidst valg, at man ikke favner alle statusværdier fra CPR-registret?

**Comment by jkiddo** [comment]
Will this be a conceptmap or just plain documentation?

**Comment by tmsMedcom** [comment]
Tilføj en tabel til dokumentationen, med en mapning fra statusværdi til koder i FHIR modellen

**Comment by Kirstinerosenbeck** [comment]
There are more statuses in cpr than I knew of. However, I believe it is fair not to include information about inactive cpr-numbers, and have included an explanation, but we should discuss this. In terms of civilstand, the Danish value 'L' is not included in our ValueSet. I do not remember why? Or it might be an error?

**Comment by jkiddo** [comment]
Civilstand is a maritalStatus in FHIR

**Comment by jkiddo** [comment]
Sorry - didnt pay enough attention to your comment. The L value is kind a weird

**Comment by jkiddo** [comment]
Its a legal thing: https://danskelove.dk/%C3%A6gteskabsloven/10
