### ISSUE TITLE
Unused lpr3 identifier

### ISSUE THREAD

**Issue by Kirstinerosenbeck** [hl7dk/dk-core#74]
We have defined this identifier https://hl7.dk/fhir/core/1.1.0/StructureDefinition-lpr3-Identifier.html, describing that it is an lpr3 identifier for an organisation. However, we do not use it anywhere.

**Comment by jkiddo** [comment]
Its for future use as it provides a sane way for parties to communicate about LPR3 CarePlans. It *could* be moved to MedCom IG's but eventually, we would need it our selves
