### ISSUE TITLE
Define release policy/governance for release/roadmap

### ISSUE THREAD

**Issue by jkiddo** [hl7dk/dk-core#79]
Inspired by the work conducted by @Kirstinerosenbeck @cauranRM and @KirstenLHDK we should define a policy and governance where we pledge to not introduce breaking changes within a certain timespan - e.g. a yearly or bi-yearly basis and also an intent of when we will update to latest released FHIR version. This could greatly help vendors and consumers in buying into our standard(s)

**Comment by jkiddo** [comment]
I recommend that we put the policy on the confluence page and link to it from the IG

**Comment by tmsMedcom** [comment]
@jkiddo is this described sufficiently in the [release process on confluence](https://confluence.hl7.org/display/HD/Release+Process+for+DK+Core) ? I will of course include a link from the IG to the release process.

**Comment by jkiddo** [comment]
I would say so, yes

**Comment by tmsMedcom** [comment]
Is handled in the [release process on confluence](https://confluence.hl7.org/display/HD/Release+Process+for+DK+Core)
