### ISSUE TITLE
Wrong ICPC system

### ISSUE THREAD

**Issue by jkiddo** [hl7dk/dk-core#80]
ICPC system identifier (https://github.com/hl7dk/dk-core/blob/695b248c249c51ebc57e6506365b97ab81398bb4/input/fsh/DkCoreCondition.fsh#L40) should be replaced with either http://terminology.hl7.org/CodeSystem/icpc-DAN or `urn:oid:2.16.840.1.113883.6.138.2` from https://terminology.hl7.org/CodeSystem-icpc-DAN.html

**Comment by Kirstinerosenbeck** [comment]
The codeSystem refered to have been retired. The Condition model have currently adopted the oid accepted by the Danish Health Data Authority as stated here: http://oid-info.com/get/1.2.208.176.2.31

**Comment by jkiddo** [comment]
Have you raised that to HL7 THO?
