### ISSUE TITLE
Performer in Observation profile is too restrictive

### ISSUE THREAD

**Issue by mbumedcom** [hl7dk/dk-core#91]
Vi er i gang med at lave en ny standard til kommunale prøvesvar, hvor vi har behov for at bruge en ikke dk-core organisation til at udtrykke performeren i standarden men det tillader dk-core-observation profil ikke.  Er der mulighed for at opbløde specificering af performer så den også indeholder en ikke dk core organisation ?

**Comment by tmsMedcom** [comment]
Not relevant at the moment
