### ISSUE TITLE
DkCoreCondition - handling of unconfirmed conditions

### ISSUE THREAD

**Issue by tmsMedcom** [hl7dk/dk-core#98]
No. 9 - fra høringssvar - besluttet: 

MedCom opretter et issue, der handler om at specificere anvendelsen af koder, der repræsenterer risici, inkl. en henvisning til eksemplet om [John mistanke om Modermærkekræft](https://hl7.dk/fhir/core/Condition-JohnMelanoma.html).

**Comment by jkiddo** [comment]
@tmsMedcom why is this still open?
